### ISSUE TITLE
How do you fetch a list of files?

### ISSUE THREAD

**Issue by biblical-text** [bramvdbogaerde/go-scp#67]
I need to first get the names of the files in the folder before I start the copy.  I cant see any function that might allow this.  What is the best way to do this?

**Comment by bramvdbogaerde** [comment]
Thank you for creating this issue. 

Currently, the library does not support fetching a list of files or directories from the remote. Instead, you will have to use the `ls` command over an existing SSH connection by parsing its output or using a full SFTP package like the one [here](https://github.com/pkg/sftp).

I am closing this issue since there are no concrete plans to support these features in the near future.
